# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
    branches:
        include:
            - master
    tags:
        include:
            - v*

strategy:
    matrix:
        linux:
            imageName: "ubuntu-16.04"

pool:
    vmImage: $(imageName)

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: "10.x"
      displayName: "Install Node.js"

    - bash: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
      displayName: Start xvfb
      condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

    - bash: |
          echo ">>> Compile vscode-test"
          yarn && yarn compile
          echo ">>> Compiled vscode-test"
          cd sample
          echo ">>> Run sample integration test"
          yarn && yarn compile && yarn test
      displayName: Run Tests
      env:
          DISPLAY: ":99.0"

    - script: |
          bash <(curl -s https://codecov.io/bash)
      displayName: Upload to codecov.io
